@ParametersAreNonnullByDefault
@MethodsAreNonnullByDefault
@FieldsAreNonnullByDefault
package com.github.ronanquillevere.airetest1.domain;

import javax.annotation.ParametersAreNonnullByDefault;
import javax.annotation.FieldsAreNonnullByDefault;
import javax.annotation.MethodsAreNonnullByDefault;
